services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db_locatel
    restart: always
    env_file:
      - ./secrets/db.env
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - db_data:/var/opt/mssql

  web:
    build: .
    container_name: app_facturacion
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html/
    depends_on:
      - db

  administrador_db:
    image: adminer
    container_name: administrador_db
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data: